connector.name=iceberg

# Use Iceberg JDBC catalog (no Hive Metastore)
iceberg.catalog.type=jdbc

# JDBC catalog settings (PostgreSQL)
iceberg.jdbc-catalog.catalog-name=icecat
iceberg.jdbc-catalog.driver-class=org.postgresql.Driver
# iceberg.jdbc-catalog.connection-url=jdbc:postgresql://iceberg-db:5432/iceberg
iceberg.jdbc-catalog.connection-url=jdbc:postgresql://iceberg-db:5432/iceberg
# iceberg.jdbc-catalog.connection-url=jdbc:postgresql://airflow-docker-postgres-1:5432/iceberg
iceberg.jdbc-catalog.connection-user=iceberg
iceberg.jdbc-catalog.connection-password=iceberg

# Default warehouse (where table data lives if LOCATION omitted)
iceberg.jdbc-catalog.default-warehouse-dir=s3://warehouse

# Trino native S3 client with MinIO
fs.native-s3.enabled=true
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.region=us-east-1
s3.aws-access-key=minioadmin
s3.aws-secret-key=minioadmin

# Parquet by default
iceberg.file-format=PARQUET